// Auto-generated by build.py — DO NOT EDIT MANUALLY
// Re-run: python build.py
// Generated: 2026-07-07T14:14:10.051933

const PORTFOLIO_DATA = {
  "categories": [
    {
      "name": "Branding",
      "slug": "branding",
      "projects": [
        {
          "id": "branding-clownnninjaszpng",
          "title": "Clown N Ninjasz",
          "category": "Branding",
          "categorySlug": "branding",
          "subProject": null,
          "imagePath": "Branding/Clown%20N%20Ninjasz.png",
          "fileName": "Clown N Ninjasz.png",
          "fileSize": 2232520
        },
        {
          "id": "branding-nivaqpng",
          "title": "Nivaq",
          "category": "Branding",
          "categorySlug": "branding",
          "subProject": null,
          "imagePath": "Branding/Nivaq.png",
          "fileName": "Nivaq.png",
          "fileSize": 1879206
        }
      ]
    },
    {
      "name": "Illustrations",
      "slug": "illustrations",
      "projects": [
        {
          "id": "illustrations-duckjpg",
          "title": "Duck",
          "category": "Illustrations",
          "categorySlug": "illustrations",
          "subProject": null,
          "imagePath": "Illustrations/Duck.jpg",
          "fileName": "Duck.jpg",
          "fileSize": 269923
        },
        {
          "id": "illustrations-mindburstpng",
          "title": "Mind Burst",
          "category": "Illustrations",
          "categorySlug": "illustrations",
          "subProject": null,
          "imagePath": "Illustrations/Mind%20Burst.png",
          "fileName": "Mind Burst.png",
          "fileSize": 1174265
        },
        {
          "id": "illustrations-oogwayjpg",
          "title": "Oogway",
          "category": "Illustrations",
          "categorySlug": "illustrations",
          "subProject": null,
          "imagePath": "Illustrations/Oogway.jpg",
          "fileName": "Oogway.jpg",
          "fileSize": 1257782
        },
        {
          "id": "illustrations-tanjiropng",
          "title": "Tanjiro",
          "category": "Illustrations",
          "categorySlug": "illustrations",
          "subProject": null,
          "imagePath": "Illustrations/Tanjiro.png",
          "fileName": "Tanjiro.png",
          "fileSize": 1418192
        },
        {
          "id": "illustrations-toonsuperherojpg",
          "title": "Toon Superhero",
          "category": "Illustrations",
          "categorySlug": "illustrations",
          "subProject": null,
          "imagePath": "Illustrations/Toon%20Superhero.jpg",
          "fileName": "Toon Superhero.jpg",
          "fileSize": 2082967
        },
        {
          "id": "illustrations-toonturtlejpg",
          "title": "Toon Turtle",
          "category": "Illustrations",
          "categorySlug": "illustrations",
          "subProject": null,
          "imagePath": "Illustrations/Toon%20Turtle.jpg",
          "fileName": "Toon Turtle.jpg",
          "fileSize": 68325
        }
      ]
    },
    {
      "name": "Logo",
      "slug": "logo",
      "projects": [
        {
          "id": "logo-clownnninjaszjpg",
          "title": "Clown N Ninjasz",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/Clown%20N%20Ninjasz.jpg",
          "fileName": "Clown N Ninjasz.jpg",
          "fileSize": 830128
        },
        {
          "id": "logo-d2ojpg",
          "title": "D2O",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/D2O.jpg",
          "fileName": "D2O.jpg",
          "fileSize": 841272
        },
        {
          "id": "logo-fmmarinajpg",
          "title": "FM Marina",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/FM%20Marina.jpg",
          "fileName": "FM Marina.jpg",
          "fileSize": 136674
        },
        {
          "id": "logo-kidsjpg",
          "title": "KIDS",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/KIDS.jpg",
          "fileName": "KIDS.jpg",
          "fileSize": 1402473
        },
        {
          "id": "logo-nivaqpng",
          "title": "Nivaq",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/Nivaq.png",
          "fileName": "Nivaq.png",
          "fileSize": 2570405
        },
        {
          "id": "logo-packeseljpg",
          "title": "Packesel",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/Packesel.jpg",
          "fileName": "Packesel.jpg",
          "fileSize": 1278790
        },
        {
          "id": "logo-rulesbotjpg",
          "title": "Rules Bot",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/Rules%20Bot.jpg",
          "fileName": "Rules Bot.jpg",
          "fileSize": 2322119
        },
        {
          "id": "logo-snuggupsjpg",
          "title": "Snuggups",
          "category": "Logo",
          "categorySlug": "logo",
          "subProject": null,
          "imagePath": "Logo/Snuggups.jpg",
          "fileName": "Snuggups.jpg",
          "fileSize": 1653058
        }
      ]
    },
    {
      "name": "Photo Manipulation & Matte Painting",
      "slug": "photo-manipulation-and-matte-painting",
      "projects": [
        {
          "id": "photomanipulationmattepainting-mattepaintingjpg",
          "title": "Matte Painting",
          "category": "Photo Manipulation & Matte Painting",
          "categorySlug": "photo-manipulation-and-matte-painting",
          "subProject": null,
          "imagePath": "Photo%20Manipulation%20%26%20Matte%20Painting/Matte%20Painting.jpg",
          "fileName": "Matte Painting.jpg",
          "fileSize": 1204416
        },
        {
          "id": "photomanipulationmattepainting-sci-fimattejpg",
          "title": "Sci Fi Matte",
          "category": "Photo Manipulation & Matte Painting",
          "categorySlug": "photo-manipulation-and-matte-painting",
          "subProject": null,
          "imagePath": "Photo%20Manipulation%20%26%20Matte%20Painting/Sci-fi%20Matte.jpg",
          "fileName": "Sci-fi Matte.jpg",
          "fileSize": 1025605
        },
        {
          "id": "photomanipulationmattepainting-tortoisejpg",
          "title": "Tortoise",
          "category": "Photo Manipulation & Matte Painting",
          "categorySlug": "photo-manipulation-and-matte-painting",
          "subProject": null,
          "imagePath": "Photo%20Manipulation%20%26%20Matte%20Painting/Tortoise.jpg",
          "fileName": "Tortoise.jpg",
          "fileSize": 6629983
        }
      ]
    },
    {
      "name": "Posters",
      "slug": "posters",
      "projects": [
        {
          "id": "posters-bmwpng",
          "title": "BMW",
          "category": "Posters",
          "categorySlug": "posters",
          "subProject": null,
          "imagePath": "Posters/BMW.png",
          "fileName": "BMW.png",
          "fileSize": 2099628
        },
        {
          "id": "posters-littlecraftspng",
          "title": "Little Crafts",
          "category": "Posters",
          "categorySlug": "posters",
          "subProject": null,
          "imagePath": "Posters/Little%20Crafts.png",
          "fileName": "Little Crafts.png",
          "fileSize": 2125724
        },
        {
          "id": "posters-mcdpng",
          "title": "M'cD",
          "category": "Posters",
          "categorySlug": "posters",
          "subProject": null,
          "imagePath": "Posters/M%27cD.png",
          "fileName": "M'cD.png",
          "fileSize": 1885154
        }
      ]
    },
    {
      "name": "Product Packaging",
      "slug": "product-packaging",
      "projects": [
        {
          "id": "productpackaging-auricaelixir-bf60tabletsjpeg",
          "title": "AURICA ELIXIR BF 60 TABLETS",
          "category": "Product Packaging",
          "categorySlug": "product-packaging",
          "subProject": null,
          "imagePath": "Product%20Packaging/AURICA%20ELIXIR-BF%2060%20TABLETS.jpeg",
          "fileName": "AURICA ELIXIR-BF 60 TABLETS.jpeg",
          "fileSize": 684083
        },
        {
          "id": "productpackaging-auricamemorycaretabletsjpeg",
          "title": "AURICA MEMORY CARE TABLETS",
          "category": "Product Packaging",
          "categorySlug": "product-packaging",
          "subProject": null,
          "imagePath": "Product%20Packaging/AURICA%20MEMORY%20CARE%20TABLETS.jpeg",
          "fileName": "AURICA MEMORY CARE TABLETS.jpeg",
          "fileSize": 630629
        },
        {
          "id": "productpackaging-auricasomni-s-01jpg",
          "title": "AURICA SOMNI S",
          "category": "Product Packaging",
          "categorySlug": "product-packaging",
          "subProject": null,
          "imagePath": "Product%20Packaging/AURICA%20SOMNI-S-01.jpg",
          "fileName": "AURICA SOMNI-S-01.jpg",
          "fileSize": 11811079
        }
      ]
    },
    {
      "name": "Sketches",
      "slug": "sketches",
      "projects": [
        {
          "id": "sketches-budhhapng",
          "title": "Budhha",
          "category": "Sketches",
          "categorySlug": "sketches",
          "subProject": null,
          "imagePath": "Sketches/Budhha.png",
          "fileName": "Budhha.png",
          "fileSize": 1105029
        },
        {
          "id": "sketches-darkpng",
          "title": "Dark",
          "category": "Sketches",
          "categorySlug": "sketches",
          "subProject": null,
          "imagePath": "Sketches/Dark.png",
          "fileName": "Dark.png",
          "fileSize": 3252991
        },
        {
          "id": "sketches-midorimapng",
          "title": "Midorima",
          "category": "Sketches",
          "categorySlug": "sketches",
          "subProject": null,
          "imagePath": "Sketches/Midorima.png",
          "fileName": "Midorima.png",
          "fileSize": 615954
        },
        {
          "id": "sketches-skullpng",
          "title": "SKull",
          "category": "Sketches",
          "categorySlug": "sketches",
          "subProject": null,
          "imagePath": "Sketches/SKull.png",
          "fileName": "SKull.png",
          "fileSize": 997301
        },
        {
          "id": "sketches-societypng",
          "title": "Society",
          "category": "Sketches",
          "categorySlug": "sketches",
          "subProject": null,
          "imagePath": "Sketches/Society.png",
          "fileName": "Society.png",
          "fileSize": 1012757
        },
        {
          "id": "sketches-ssrpng",
          "title": "SSR",
          "category": "Sketches",
          "categorySlug": "sketches",
          "subProject": null,
          "imagePath": "Sketches/SSR.png",
          "fileName": "SSR.png",
          "fileSize": 380574
        }
      ]
    },
    {
      "name": "Social Media Post",
      "slug": "social-media-post",
      "projects": [
        {
          "id": "socialmediapost-socialmediapost1jpg",
          "title": "Social Media Post 1",
          "category": "Social Media Post",
          "categorySlug": "social-media-post",
          "subProject": null,
          "imagePath": "Social%20Media%20Post/Social%20Media%20Post%201.jpg",
          "fileName": "Social Media Post 1.jpg",
          "fileSize": 573431
        },
        {
          "id": "socialmediapost-socialmediapost2jpg",
          "title": "Social Media Post 2",
          "category": "Social Media Post",
          "categorySlug": "social-media-post",
          "subProject": null,
          "imagePath": "Social%20Media%20Post/Social%20Media%20Post%202.jpg",
          "fileName": "Social Media Post 2.jpg",
          "fileSize": 528560
        },
        {
          "id": "socialmediapost-socialmediapost3jpg",
          "title": "Social Media Post 3",
          "category": "Social Media Post",
          "categorySlug": "social-media-post",
          "subProject": null,
          "imagePath": "Social%20Media%20Post/Social%20Media%20Post%203.jpg",
          "fileName": "Social Media Post 3.jpg",
          "fileSize": 549462
        },
        {
          "id": "socialmediapost-socialmediapost4jpg",
          "title": "Social Media Post 4",
          "category": "Social Media Post",
          "categorySlug": "social-media-post",
          "subProject": null,
          "imagePath": "Social%20Media%20Post/Social%20Media%20Post%204.jpg",
          "fileName": "Social Media Post 4.jpg",
          "fileSize": 121946
        },
        {
          "id": "socialmediapost-socialmediapost5jpg",
          "title": "Social Media Post 5",
          "category": "Social Media Post",
          "categorySlug": "social-media-post",
          "subProject": null,
          "imagePath": "Social%20Media%20Post/Social%20Media%20Post%205.jpg",
          "fileName": "Social Media Post 5.jpg",
          "fileSize": 702847
        },
        {
          "id": "socialmediapost-socialmediapost6png",
          "title": "Social Media Post 6",
          "category": "Social Media Post",
          "categorySlug": "social-media-post",
          "subProject": null,
          "imagePath": "Social%20Media%20Post/Social%20Media%20Post%206.png",
          "fileName": "Social Media Post 6.png",
          "fileSize": 1928119
        }
      ]
    }
  ]
};
